name: mpj_job_printer
description: "MPJ Job Order Form Printer (Flutter Windows Desktop)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  path_provider: ^2.1.3
  window_manager: ^0.3.8
  intl: ^0.19.0
  charset_converter: ^2.1.1
  pdf: ^3.12.0
  printing: ^5.14.3
  get: ^4.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Kanit-Regular.ttf